#!/bin/sh

ANDROID_STORE_CACHE=~/.soomla/cache/android-store
mkdir -p $ANDROID_STORE_CACHE

if [ ! -f libs/in-app-purchasing-2.0.1.jar ];
then
    if [ ! -f $ANDROID_STORE_CACHE/in-app-purchasing-2.0.1.jar ];
    then
        curl -L -o $ANDROID_STORE_CACHE/in-app-purchasing-2.0.1.jar.tmp http://library.soom.la/fetch/android-store-in-app-purchasing/2.0.1?cf=dl_deps
        mv $ANDROID_STORE_CACHE/in-app-purchasing-2.0.1.jar.tmp $ANDROID_STORE_CACHE/in-app-purchasing-2.0.1.jar
    fi
    cp $ANDROID_STORE_CACHE/in-app-purchasing-2.0.1.jar libs/in-app-purchasing-2.0.1.jar
fi